### ISSUE TITLE
Activity is set only inactive when next Activity is "run", i.e. its runNext() is called.

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#55] opened 2015-08-30 21:24 UTC
Check CAExecutionTest 'Execute ElemAct using Done transition' test method.

It seems that State.isFinished and Transition.finishing flags of StateMachine are not used. This might not be a bug, but resolving this functionality could simplify AdvancementCalculator

**Comment by abranson** [comment] 2015-09-01 08:29
To clarify, this relates to the way in which the active flag is transferred between activities. By design, the flag is not deactivated on a completed activity until another one has been activated. This means that the last activity of a workflows will stay active when the workflow is complete.

**Comment by abranson** [comment] 2015-09-16 09:07
By design

**Closed by abranson** 2015-09-16 09:07 UTC
Labels: invalid
