### ISSUE TITLE
kernel bootstrap : warning appears with Java 8

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#44] opened 2015-08-18 07:24 UTC
When running the kernel with Java 8, the following warning appears for each call to te "verifyResource()" during the bootstrap phase.
```
Bootstrap.run() setContextClassLoader=[sun.misc.Launcher$AppClassLoader@387f44]
Bootstrap.run() - Verifying kernel boot data items
Verifying kernel boot items
Bootstrap.verifyResource() - Verifying version 0 of StateMachine Default
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Avertissements de compilateur :
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
```

**Comment by abranson** [comment] 2015-08-26 10:18
This happens on all XML parsing. I think this is some sort of conflict between the version of Xerces we are using and the version bundled in the Java runtime.

**Comment by abranson** [comment] 2015-09-01 12:53
It seems that the Apache version of Xerces is no longer maintained, and does not support the more recent properties of JAXP. The solution seems to be to drop the dependency and use the one bundled with the Java runtime. Unfortunately Castor cannot use that version for serializing documents, so we're stuck with it for the time being.

I've removed all of our usage of the external Xerces lib, so if a later version of Castor will work without it, then we can drop it.

**Comment by debbabi** [comment] 2015-09-08 13:36
@Andy, I have this exception when calling the Gateway.init(..)
````
EXCEPTION:java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:194)
	at org.cristalise.kernel.persistency.outcome.OutcomeValidator.<init>(OutcomeValidator.java:81)
	at org.cristalise.kernel.process.module.ModuleManager.<init>(ModuleManager.java:56)
	at org.cristalise.kernel.process.Gateway.init(Gateway.java:138)
````
I think it is related to the latest changes you have made on this issue.

**Comment by abranson** [comment] 2015-09-08 13:52
Very probably. Do you have any jaxp config set up already? The method for resolving schemas is detailed in the javadoc:

http://docs.oracle.com/javase/7/docs/api/javax/xml/validation/SchemaFactory.html#newInstance%28java.lang.String%29

If there's anything making it fail to set up the schema parser, it will throw that error. Unless there's some stray config in my dependencies that I'm unaware of, it should work.

**Comment by debbabi** [comment] 2015-09-08 14:03
I have not yet put any config for jaxp, I missed this update on the kernel, I have always Xerces bundles on my runtime. I will try to configure it.

**Comment by abranson** [comment] 2015-09-08 14:11
Yeah, the purpose of all this was to remove the Apache Xerces bundles, as lots of projects seem to be doing right now. I don't think just removing the jar will fix it though - I don't get this error if I put it back, just the hundreds of warnings again. See if you have a jaxp.properties hidden away somewhere.

**Comment by ogattaz** [comment] 2015-09-08 15:54
The initial problem that Sandra has reported was warnings in the traces  
eg
``` 
2015/09/08; 17:45:37:356; WARNING;     Bootstrapper; xolab.castor.xml.Marshaller;          processAttribute; Error getting value from org.cristalise.kernel.lifecycle.instance.Workflow@35110099
```
Do not you think that the problem could be solved by adjustment in the castor's mapping files ?

**Comment by debbabi** [comment] 2015-09-08 16:15
@abranson I tried lot of solutions to get the JAXP working under OSGi. It is not as simple as I thinked. The JAXP is not intended to be used under OSGI yet, it is rather made of JVM services (providing Factories). The same problem I have is described here https://java.net/jira/browse/GLASSFISH-19579.
The guys gives some workarounds but no concrete solutions.

It is highly recommended to get things back as it was before (dependencies to XERCES) until JAXP will get more support to OSGi runtime. Hopes that the set of new features brought by JAXP are not mondatory for the Cristal Kernel.

**Comment by abranson** [comment] 2015-09-08 17:08
@debbabi Ok that is disappointing - this should have been an internal change within the kernel that should not impact anything else.

The problem is that these warning are symptomatic of the fact that Xerces is no longer supported and has not seen a new release in five years. Many projects are dropping it in favour of the version included in the Java runtime, like I did here. We need to move away from it.

**Comment by abranson** [comment] 2015-09-08 19:03
That Glassfish bug is old, and seems to refer to the use of JAXP as an external jar before it was included in the Java runtime. This looks more like your bug:
http://karaf.922171.n3.nabble.com/Unable-to-launch-karaf-2-3-0-td4027451.html
And only requires the setting of a system property to fix. Did you try that?

**Comment by abranson** [comment] 2015-09-14 12:31
Seems to be ok now...

**Closed by abranson** 2015-09-14 12:31 UTC
